### ISSUE TITLE
似乎不支援最新版的 Twitch

### ISSUE THREAD

**Issue by pc035860** [wheatup/TwitchChatDanmaku#1]
我安裝了 1.4.2 版，在最新版 Twitch 網站上沒有出現彈幕。

翻了一下 source code ，似乎是 `createOverlay()` 裡面沒有包含適用最新版網站的選擇器，我本地測試可用的選擇器是 `.video-player__container`。

![image](https://user-images.githubusercontent.com/811518/66504147-2631ce80-eafb-11e9-8061-08f8c3381c50.png)

**Comment by wheatup** [comment]
奇怪，不同的用户播放器的class不一样的吗？
我试着更新了一下，加入了更多可能的class，你试试更新到1.4.3版本还有没有弹幕出现

**Comment by pc035860** [comment]
1.4.3 沒有問題囉  感謝
