### ISSUE TITLE
真的是非常讚的直播彈幕系統,有沒有考慮增加個FireFox的支持?

### ISSUE THREAD

**Issue by telanxrays** [wheatup/TwitchChatDanmaku#3]
我平時也經常用FireFox瀏覽器,奈何這插件沒有FF版本,只能用chrome看直播.
收藏代碼研究研究原理,奈何自己水平不高,不知道怎麼轉成FF插件.
總之感謝開發,真的很有用.

**Comment by wheatup** [comment]
不好意思剛看到。
FF個人沒怎麼用過，沒有開發插件的經驗。
不過除了和瀏覽器通信這一邊需要重寫以外，大多數代碼都通用，畢竟都是javascript和css。
有時間會研究一下。

**Comment by pc035860** [comment]
Firefox 現在採用的插件標準是 Web Extension，大部分都能與 Chrome API 相容。

我本來有打算來幫忙 port 一下，試了試要轉到 Firefox 的話有兩個 Chrome API 不支援：

- chrome.declarativeContent
- chrome.fontSettings

`declarativeContent` 的部分有 workaround 可以解決，但 `fontSettings` 沒有，所以 Firefox 版可能需要把自選字型的這部分功能拿掉。

兩個不支援的 API 解決之後應該就完成 9 成了，其它部分大概都不用動。

**Comment by telanxrays** [comment]
@wheatup @pc035860 謝謝兩位大佬,辛苦了.

**Comment by spphinslove** [comment]
没有消息了吗？
